name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: mymindstorm/setup-emsdk@v11

      - name: Fetch and build Lua source code
        run: make libraries

      - name: Build application in production mode
        run: make prod

      - name: Commit built files to gh-pages branch
        run: |
          git fetch origin
          git checkout gh-pages
          git pull
          cp -r build docs
          git add docs
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
          git push
